language: c++
sudo: true
dist: trusty
services:
  - docker
cache:
  directories:
    - $HOME/.ccache
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    - ROS_PARALLEL_JOBS="-j8"
    - ROS_PARALLEL_TEST_JOBS="-j8"
    - CATKIN_PARALLEL_TEST_JOBS="-p4"
    - NOT_TEST_INSTALL=true
    - USE_JENKINS=false
    - USE_TRAVIS=true
    - USE_DOCKER=true
  matrix:
    - ROS_DISTRO=melodic USE_DEB=true
script: source .travis/travis.sh

branches:
  only:
    - master
